USW-Flag-Board/Backend

- src/main/java/com/FlagHome/backend/v1/reply/entity/Reply.java
- group, order, detph 컬럼들 추가
- 해당 컬럼들로 댓글,대댓글 관계 표현 가능
> [개선] Reply Entity 개선 (2022.10.25 윤희승)

- src/main/java/com/FlagHome/backend/v1/config/QueryDslConfig.java
- src/main/java/com/FlagHome/backend/v1/reply/controller/ReplyController.java
- src/main/java/com/FlagHome/backend/v1/reply/entity/Reply.java
- src/main/java/com/FlagHome/backend/v1/reply/repository/ReplyRepository.java
- src/main/java/com/FlagHome/backend/v1/reply/repository/ReplyRepositoryCustom.java
- src/main/java/com/FlagHome/backend/v1/reply/repository/ReplyRepositoryImpl.java
- src/main/java/com/FlagHome/backend/v1/reply/service/ReplyService.java
- QueryDslConfig 추가
- QueryDsl을 이용한 reply 가져오기 추가
> [추가/개선] QueryDsl설정 추가 및 Reply 대응 (2022.10.27 윤희승)

- src/main/java/com/FlagHome/backend/v1/reply/controller/ReplyController.java
- src/main/java/com/FlagHome/backend/v1/reply/dto/ReplyDto.java
- src/main/java/com/FlagHome/backend/v1/reply/service/ReplyService.java
- src/test/java/com/FlagHome/backend/v1/reply/controller/ReplyControllerTest.java
- ReplyDto 추가
- Reply를 Create 할수 있게끔 대응
- 컨트롤러에 맞는 테스트 코드 추가
> [추가/개선] Create Reply 대응 (2022.11.07 윤희승)

- src/main/java/com/FlagHome/backend/v1/reply/controller/ReplyController.java
- src/main/java/com/FlagHome/backend/v1/reply/service/ReplyService.java
- src/test/java/com/FlagHome/backend/v1/reply/controller/ReplyControllerTest.java
- Reply를 Update(Modify) 할수 있게끔 대응
> [추가/개선] Update Reply 대응 (2022.11.08 윤희승)

- src/main/java/com/FlagHome/backend/v1/post/dto/PostDto.java
- src/main/java/com/FlagHome/backend/v1/token/entity/RefreshToken.java
- src/test/java/com/FlagHome/backend/v1/post/controller/PostControllerTest.java
- 모든분들 master branch에는 반드시 프로젝트 전체 빌드 테스트 하고 올려주세요 ㅠㅠ
> [개선] 빌드오류 발생 부분 해결 (2022.11.29 윤희승)

- README.md
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/util/ShaEncoder.java
- src/main/java/com/FlagHome/backend/v1/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/v1/auth/dto/LoginRequest.java
- src/main/java/com/FlagHome/backend/v1/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/v1/member/repository/MemberRepository.java
- src/main/java/com/FlagHome/backend/v1/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/v1/reply/controller/ReplyController.java
- src/main/java/com/FlagHome/backend/v1/token/service/RefreshTokenService.java
- src/test/java/com/FlagHome/backend/v1/auth/AuthServiceTest.java
1. 혹시 로그인 기능을 AuthorizationFilter를 만들어서 처리하는 방식은 어떤가요?
2. Java 17 버전을 사용한 이유도 궁금합니다!
> pullling project By K-Diger

- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/v1/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/v1/member/repository/MemberRepository.java
- src/main/java/com/FlagHome/backend/v1/post/service/PostService.java
- src/main/java/com/FlagHome/backend/v1/reply/dto/ReplyDto.java
- src/main/java/com/FlagHome/backend/v1/reply/service/ReplyService.java
- src/test/java/com/FlagHome/backend/v1/post/controller/PostControllerTest.java
- src/test/java/com/FlagHome/backend/v1/reply/controller/ReplyControllerTest.java
- URI변경에 따라 테스트코드 대응
- 기존 ExceptionHandler 미사용하던 코드들 사용하게끔 대응
- AuthService에서 existsByLoginId 사용시 에러 발생하여 수정
> [개선] 바뀐 URI에 따른 테스트코드 대응 및 Exception 처리 (2022.12.06 윤희승)

- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/Role.java
- src/main/java/com/FlagHome/backend/domain/member/entity/Member.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/config/SwaggerConfig.java
- Securtiy 인증 수정
- Swagger 패키지 수정
> [개선] Config 개선 (2022.12.24 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/Proceed.java
- src/main/java/com/FlagHome/backend/domain/activity/Status.java
- src/main/java/com/FlagHome/backend/domain/activity/Type.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Activity.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/mail/MailType.java
- src/main/java/com/FlagHome/backend/domain/mail/dto/MailRequest.java
- src/main/java/com/FlagHome/backend/domain/mail/service/MailService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/global/util/RandomGenerator.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- Activity 엔티티 개선,  Enum 분리 (status)
- Activity Controller, Service 추가
- Mail 패키지 구조 변경, un-import 문 제거
> [추가, 개선, 리팩토링] Activity 개선, Mail 패키지 변경 (2022.12.26 문희조)

- src/main/java/com/FlagHome/backend/domain/admin/controller/AdminController.java
- src/main/java/com/FlagHome/backend/domain/admin/service/AdminService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/mail/service/MailService.java
- src/main/java/com/FlagHome/backend/domain/member/Role.java
- src/main/java/com/FlagHome/backend/domain/member/entity/Member.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/report/Service/RepostService.java
- src/main/java/com/FlagHome/backend/domain/report/entity/Report.java
- src/main/java/com/FlagHome/backend/domain/report/repository/ReportRepository.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- Admin 멤버 상태 관리 추가 (밴, 탈퇴)
- 신고 패키지 추가
- 테스트 코드 작성
> [추가, 테스트] 관리자 기능, 신고 패키지, 테스트 코드 추가 (2022.12.30 문희조)

- src/main/java/com/FlagHome/backend/domain/category/repository/CategoryRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/category/repository/CategoryRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/post/dto/PostDto.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepository.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/search/controller/BoardSearchController.java
- src/main/java/com/FlagHome/backend/domain/search/enums/SearchType.java
- src/main/java/com/FlagHome/backend/domain/search/service/SearchService.java
- src/main/java/com/FlagHome/backend/domain/search/service/impl/BoardSearchService.java
- src/test/java/com/FlagHome/backend/domain/search/SearchTest.java
- SearchController는 현재 뼈대만 제작
- Service 위주로 구현
> [추가] Search 패키지 추가 (2022.12.30 윤희승)

- appspec.yml
- github action 문제 해결 (#53)
- CD 에러 수정
> [버그] CD 에러 수정 (2023.1.3 문희조)

- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/withdrawal/entity/Withdrawal.java
- src/main/java/com/FlagHome/backend/domain/withdrawal/repository/WithdrawalRepository.java
- 탈퇴 멤버 id값 제외하고 모두 암호화
- 2주동안 로그인안하면 휴면 계정 전환
> [추가] 탈퇴 멤버 정보 암호화, 휴면계정 전환(2023.01.07 이화영)

- deploy.sh
- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthMemberService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/dto/ProfileResponse.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/config/SwaggerConfig.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/utility/UriCreator.java
- src/main/resources/application.yml
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- 프로필 정보 가져오기 추가
- UriCreator.createMemberUri 추가
- 멤버 검증 URI 수정
> [추가, 수정] 멤버 프로필 가져오기, 멤버 uri 가져오기 추가/멤버 URI 수정 (2023.1.10 문희조)

- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/post/service/PostService.java
- src/test/java/com/FlagHome/backend/domain/post/controller/PostControllerTest.java
- src/test/java/com/FlagHome/backend/domain/post/controller/PostControllerTestAsSlice.java
- 현재 컨셉에 맞춰 content, replyList만 들고올수 있게끔 파라미터를 추가 하였습니다.
> [개선] Post의 getPost메서드에 파라미터 추가 (2023.01.12 윤희승)

- .github/workflows/workflow.yml
- Git 히스토리 삭제에 따라 CD application-db.yml 업로드 추가
> [수정] CD 시 application-db.yml 생성 추가 (2023.1.14 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityApply/repository/ActivityApplyRepository.java
- src/main/java/com/FlagHome/backend/domain/activity/activityApply/repository/ActivityApplyRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/activity/activityApply/repository/ActivityApplyRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/activityApply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthMemberService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/report/Service/ReportService.java
- src/main/java/com/FlagHome/backend/domain/report/controller/ReportController.java
- src/main/java/com/FlagHome/backend/domain/report/dto/ReportRequest.java
- src/main/java/com/FlagHome/backend/domain/report/entity/Report.java
- src/main/java/com/FlagHome/backend/domain/report/repository/ReportRepository.java
- src/main/java/com/FlagHome/backend/domain/report/repository/ReportRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/report/repository/ReportRepositoryImpl.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/config/WebConfig.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- CORS 설정 추가
- 신고 Swagger 추가 및 검증 로직 수정
> [추가] CORS, 신고 Swagger 추가 (2023.1.23 문희조)

- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/dto/CheckEmailRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/dto/JoinResponse.java
- src/main/java/com/FlagHome/backend/domain/auth/repository/AuthRepository.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/mail/service/MailService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/report/entity/Report.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthServiceTest.java
- 인증메일 재발송 이슈로 로직 병합 (테스트 코드 미작성)
- 인증정보를 가져올 때 unique한 값을 가져오도록 변경
> [수정] SendMail, Join 로직 수정 (2023.1.23 문희조)

- src/main/java/com/FlagHome/backend/domain/reply/controller/ReplyController.java
- src/test/java/com/FlagHome/backend/domain/reply/controller/ReplyControllerTest.java
- ReplyControllerTest에서 세부적인 테스트코드 구현이 필요한 부분은 주석처리 해놓았으며, 곧 구현 예정 입니다.
> [개선] Reply 컨트롤러 리턴 HttpResponse로 대체 (2023.01.25 윤희승)

- src/main/java/com/FlagHome/backend/domain/like/entity/Like.java
- src/main/java/com/FlagHome/backend/domain/like/entity/LikeDto.java
- src/main/java/com/FlagHome/backend/domain/like/enums/LikeType.java
- src/main/java/com/FlagHome/backend/domain/like/repository/LikeRepository.java
- src/main/java/com/FlagHome/backend/domain/like/service/LikeService.java
- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/post/dto/PostDto.java
- src/main/java/com/FlagHome/backend/domain/post/entity/Post.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/post/controller/PostControllerTest.java
- src/test/java/com/FlagHome/backend/domain/post/controller/PostControllerTestAsSlice.java
> [추가] Post 좋아요 기능 추가 (2023.01.26 윤희승)

- src/main/java/com/FlagHome/backend/domain/Status.java
- src/main/java/com/FlagHome/backend/domain/activity/activityapply/repository/ActivityApplyRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/auth/dto/JoinRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/entity/AuthInformation.java
- src/main/java/com/FlagHome/backend/domain/auth/repository/AuthRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/auth/repository/AuthRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthInformationService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/mail/service/MailService.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/dto/AvatarResponse.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/entity/Avatar.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/repository/AvatarRepository.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/repository/AvatarRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/repository/AvatarRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/service/AvatarService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/dto/MyPageResponse.java
- src/main/java/com/FlagHome/backend/domain/member/entity/Member.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/withdrawal/entity/Sleeping.java
- src/main/java/com/FlagHome/backend/domain/withdrawal/repository/WithdrawalRepository.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- 멤버 엔티티 개인 정보 삭제, 아바타로 분리 (#136)
> [추가, 수정] 멤버 엔티티 수정, 아바타 추가 (2023.1.27 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/activity/dto/GetAllActivitiesResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceSliceTest.java
> [수정, 테스트] 스프링 시큐리티 최신화, 활동 테스트 코드 작성 (2023.1.30 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/repository/ActivityApplyRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/activity/activityapply/repository/ActivityApplyRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/activityapply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/dto/ParticipantResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/entity/MemberActivity.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/repository/MemberActivityRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/repository/MemberActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/service/MemberActivityService.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/dto/LoginLogResponse.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityApplyServiceTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- 활동장 넘기기 시 구성원인지 확인 로직 추가
- 활동장 인원 관리용 구성원 보기 추가
- 마감 시 신청내역 삭제하도록 추가
- 신청 취소 시 바로 삭제하도록 수정
- 테스트 코드 마무리
> [추가, 수정, 테스트] 활동 기능 추가 및 일부 수정, 멤버 기능 수정 (2023.1.31 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceSliceTest.java
- 아이디 찾기 시 이름도 비교
- 인증 시 리턴 값 변경
> [수정] 아이디 찾기, 인증 수정 (2023.1.31 문희조)

- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
> [수정] 시큐리티 설정 수정 (2023.1.31 문희조)

- src/main/java/com/FlagHome/backend/domain/mail/dto/MailRequest.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceSliceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
> [수정] 이메일 응답 수정, CORS 대응 (2023.2.2 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/common/ApplicationResponse.java
- src/main/java/com/FlagHome/backend/domain/file/controller/FileController.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/dto/WithdrawRequest.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/reply/controller/ReplyController.java
- src/main/java/com/FlagHome/backend/domain/report/controller/ReportController.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- src/test/java/com/FlagHome/backend/domain/post/controller/PostControllerTest.java
- 리턴 DTO 볼 수 있게 컨트롤러 수정
- 중복체크 예외 던지기 -> Boolean 리턴
> [수정] 멤버 컨트롤러 수정, 중복체크 리턴 변경 (2023.2.4 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/dto/GetAllActivitiesResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/member/dto/FindResponse.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtUtilizer.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceSliceTest.java
- 컨트롤러 ResponseEntity 제거, Response 수정
> [수정] 활동 컨트롤러, 토큰 발급 시간 수정 (2023.2.7 문희조)

- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtUtilizer.java
> [수정] 토큰 유효성 검사 수정 (2023.2.7 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/admin/controller/AdminController.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/post/service/PostService.java
- src/main/java/com/FlagHome/backend/domain/token/service/RefreshTokenService.java
> [버그] 토큰 버그 수정, api uri 수정 (2023.2.10 문희조)

- src/main/java/com/FlagHome/backend/domain/token/entity/Token.java
- src/main/java/com/FlagHome/backend/domain/token/service/RefreshTokenService.java
- 토큰 재발급 시 업데이트 시간 변경
- 토큰 검증 책임 변경
> [수정] 토큰 재발급 수정 (2023.2.10 문희조)

- src/main/java/com/FlagHome/backend/domain/token/service/RefreshTokenService.java
> [수정] Refresh토큰 저장 수정 (2023.2.10 문희조)

- build.gradle
- src/main/java/com/FlagHome/backend/domain/activity/ActivityType.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Activity.java
- src/main/java/com/FlagHome/backend/domain/activity/mapper/ActivityMapper.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/admin/controller/AdminController.java
- src/main/java/com/FlagHome/backend/domain/admin/service/AdminService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/entity/Member.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/member/sleeping/repository/SleepingRepository.java
- src/main/java/com/FlagHome/backend/domain/member/sleeping/service/SleepingService.java
- src/main/java/com/FlagHome/backend/global/config/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtUtilizer.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/sleeping/SleepingServiceTest.java
- 로그인 401 Error 수정 (로직 오류)
- 활동 서비스 DTO 의존성 분리 (+ mapper 추가)
- 캡슐화 적용 : 로그인, 회원 중복 검사, 회원 생성
- 서비스 불필요한 의존성 제거 (인증,관리자,휴면)
> [추가, 개선] 활동 Mapper 추가, 로그인 수정 (2023.03.06 문희조)

- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/entity/AuthInformation.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthInformationService.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/entity/Avatar.java
- src/main/java/com/FlagHome/backend/domain/member/avatar/service/AvatarService.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- 인증시간 10분으로 설정
- 불필요한 주석, 잘못된 타입 수정
- 캡슐화 적용 : 아바타 서비스
> [추가] 회원가입 인증 만료 추가 (2023.03.08 문희조)

- src/main/java/com/FlagHome/backend/domain/auth/controller/dto/CheckLoginIdRequest.java
- src/main/java/com/FlagHome/backend/global/annotation/USWEmailValidator.java
- src/main/java/com/FlagHome/backend/global/config/security/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorResponse.java
- src/main/java/com/FlagHome/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/FlagHome/backend/global/infra/aws/s3/service/FileService.java
- 유효성 검사 실패 핸들러 추가
- 불필요한 에러 삭제 (NOT_EMAIL)
- USW email 검증 로직 변경
> [추가, 수정] 예외 핸들러 추가, 불필요한 에러 삭제 (2023.03.19 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/ActivityResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Activity.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Mentoring.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Project.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Study.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/enums/ActivityStatus.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/enums/ActivityType.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/enums/Proceed.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/enums/Semester.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/enums/Status.java
- src/main/java/com/FlagHome/backend/domain/activity/mapper/ActivityMapper.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/dto/ParticipateResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/repository/MemberActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/board/mapper/BoardMapper.java
- src/main/java/com/FlagHome/backend/domain/member/mapper/MemberMapper.java
- src/main/java/com/FlagHome/backend/domain/reply/service/ReplyService.java
- src/main/java/com/FlagHome/backend/global/common/Status.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/infra/aws/s3/AwsS3Service.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityApplyServiceTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- 활동 학기 Enum 추가 (기존 String에서 분리 및 하드 코딩 제거)
- Enum 영어로 통일하도록 수정
- S3 contentLength 에러 수정
> [추가, 수정] Enum 추가 및 수정, 파일 업로딩 수정 (2023.03.24 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/board/controller/BoardController.java
- src/main/java/com/FlagHome/backend/domain/member/entity/enums/Role.java
- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/report/controller/ReportController.java
- src/main/java/com/FlagHome/backend/domain/token/entity/RefreshToken.java
- src/main/java/com/FlagHome/backend/domain/token/service/RefreshTokenService.java
- src/main/java/com/FlagHome/backend/global/config/security/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtUtilizer.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityControllerTest.java
- 활동 컨트롤러 테스트 추가
- Security Path 수정 (추후 추가 개선 예정)
- 토큰 테스트 기간 종료
> [추가, 수정] 활동 테스트, Security 개선, 토큰 테스트 종료 (23.03.30 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/global/config/security/SecurityConfig.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtAccessDeniedHandler.java
- src/main/java/com/FlagHome/backend/global/jwt/JwtAuthenticationEntryPoint.java
- 중복 테스트 한번 더 진행
- Config 가독성, WARN 수정
> [추가, 수정] 회원가입 유효성 검증 추가, SecurityConfig 수정 (23.4.1 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/board/service/BoardService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/AvatarResponse.java
- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/post/controller/dto/PostRequest.java
- src/main/java/com/FlagHome/backend/domain/post/controller/dto/PostResponse.java
- src/main/java/com/FlagHome/backend/domain/post/entity/Post.java
- src/main/java/com/FlagHome/backend/domain/post/entity/PostStatus.java
- src/main/java/com/FlagHome/backend/domain/post/mapper/PostMapper.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/post/service/PostService.java
- src/main/java/com/FlagHome/backend/domain/reply/service/ReplyService.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/entity/File.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/entity/FileStatus.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/repository/FileRepository.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityControllerTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/member/sleeping/SleepingServiceTest.java
- src/test/java/com/FlagHome/backend/domain/post/PostControllerTest.java
- src/test/java/com/FlagHome/backend/domain/post/PostServiceTest.java
- src/test/java/com/FlagHome/backend/domain/report/ReportRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/token/TokenRepositoryTest.java
> [추가] 게시글 기본 기능 추가 (23.04.08 문희조)

- src/main/java/com/FlagHome/backend/domain/auth/AuthInformation.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/AuthController.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/dto/CheckLoginIdRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/dto/JoinRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/dto/LoginRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/controller/dto/SignUpRequest.java
- src/main/java/com/FlagHome/backend/domain/auth/service/AuthService.java
- src/main/java/com/FlagHome/backend/domain/member/entity/Member.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/post/entity/Post.java
- src/main/java/com/FlagHome/backend/domain/post/service/PostService.java
- src/main/java/com/FlagHome/backend/domain/token/dto/TokenRequest.java
- src/main/resources/application.yml
- src/test/java/com/FlagHome/backend/domain/auth/AuthControllerTest.java
- src/test/java/com/FlagHome/backend/domain/auth/AuthServiceTest.java
- src/test/java/com/FlagHome/backend/domain/member/MemberServiceTest.java
- src/test/java/com/FlagHome/backend/domain/post/PostControllerTest.java
- Connection 10 -> 20
- 통합 테스트 추가
- 캡슐화 추가
> [추가] DTO Validation 추가, Thread Connection 확장 (23.04.09 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/entity/ActivityApply.java
- src/main/java/com/FlagHome/backend/domain/activity/activityapply/service/ActivityApplyService.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/ActivityRequest.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/service/MemberActivityService.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/AuthenticationRequest.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/FindIdRequest.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/FindPasswordRequest.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/FindResponse.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/MyProfileResponse.java
- src/main/java/com/FlagHome/backend/domain/member/controller/dto/UpdateAvatarRequest.java
- src/main/java/com/FlagHome/backend/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/domain/post/controller/PostController.java
- src/main/java/com/FlagHome/backend/domain/post/controller/dto/PostResponse.java
- src/main/java/com/FlagHome/backend/domain/post/entity/Post.java
- src/main/java/com/FlagHome/backend/domain/post/entity/enums/PostStatus.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/post/repository/PostRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/post/service/PostService.java
- src/main/java/com/FlagHome/backend/global/exception/ErrorCode.java
- src/test/java/com/FlagHome/backend/domain/post/PostControllerTest.java
- src/test/java/com/FlagHome/backend/domain/post/PostRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/post/reply/ReplyControllerTest.java
- src/test/java/com/FlagHome/backend/domain/post/reply/ReplyRepositoryTest.java
- 파라미터에 따라 좋아요 혹은 최신순으로 리턴
- Valid 오류 수정
- 내 상세정보에 로그인 아이디 추가
> [추가, 수정] 탑 게시글 가져오기 추가, 프론트 요구 대응 (23.04.17 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/activityapply/repository/ActivityApplyRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/request/ChangeLeaderRequest.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/request/CloseRecruitRequest.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/response/GetAllActivitiesResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Activity.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Mentoring.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Project.java
- src/main/java/com/FlagHome/backend/domain/activity/entity/Study.java
- src/main/java/com/FlagHome/backend/domain/activity/memberactivity/repository/MemberActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryCustom.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/activity/service/ActivityService.java
- src/main/java/com/FlagHome/backend/domain/auth/AuthInformation.java
- src/main/java/com/FlagHome/backend/domain/member/controller/MemberController.java
- src/main/java/com/FlagHome/backend/domain/member/service/MemberService.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/entity/File.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/entity/enums/FileDirectory.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/entity/enums/FileStatus.java
- src/main/java/com/FlagHome/backend/infra/aws/s3/service/AwsS3Service.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityRepositoryTest.java
- src/test/java/com/FlagHome/backend/domain/activity/ActivityServiceTest.java
- 모집 중인 활동 가져오기 추가 (홈페이지 띄우기)
- 파일 경로 enum으로 관리하도록 변경
> [추가] 모집 중인 활동 가져오기, 파일 경로 추가 (23.04.18 문희조)

- src/main/java/com/FlagHome/backend/domain/activity/controller/ActivityController.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/request/ActivityRequest.java
- src/main/java/com/FlagHome/backend/domain/activity/controller/dto/response/ActivityDetailResponse.java
- src/main/java/com/FlagHome/backend/domain/activity/mapper/ActivityMapper.java
- src/main/java/com/FlagHome/backend/domain/activity/repository/ActivityRepositoryImpl.java
- src/main/java/com/FlagHome/backend/domain/board/entity/enums/BoardType.java
> [수정] 활동 가져오기 수정 (23.04.21 문희조)

- src/main/java/com/Flaground/backend/global/config/SwaggerConfig.java
- src/main/java/com/Flaground/backend/global/exception/ErrorCode.java
- src/main/java/com/Flaground/backend/module/activity/service/ActivityService.java
- src/main/java/com/Flaground/backend/module/board/controller/BoardController.java
- src/main/java/com/Flaground/backend/module/board/service/BoardService.java
- src/main/java/com/Flaground/backend/module/member/controller/MemberController.java
- src/main/java/com/Flaground/backend/module/member/domain/Avatar.java
- src/main/java/com/Flaground/backend/module/member/domain/Member.java
- src/main/java/com/Flaground/backend/module/member/service/MemberScheduleService.java
- src/main/java/com/Flaground/backend/module/member/service/MemberService.java
- src/main/java/com/Flaground/backend/module/member/service/SleepingService.java
- src/main/java/com/Flaground/backend/module/post/service/PostService.java
- 프로필 이미지 기본으로 돌리기 추가
- 스케쥴 처리용 멤버 서비스 추가
- 게시판 중복 유효성 검사 추가
>  [추가] 기본 이미지로 돌리기, 게시판 유효성 검사 추가 (23.05.09 문희조)

- src/main/java/com/Flaground/backend/module/post/domain/Post.java
- src/main/java/com/Flaground/backend/module/post/domain/enums/TopPostCondition.java
- src/main/java/com/Flaground/backend/module/post/domain/repository/implementation/PostRepositoryImpl.java
- src/test/java/com/Flaground/backend/module/post/PostControllerTest.java
> [버그] 게시글 상세보기 버그 수정 (23.05.13 문희조)

- src/main/java/com/Flaground/backend/global/common/ApplicationResponse.java
- src/main/java/com/Flaground/backend/module/member/controller/MemberController.java
- src/main/java/com/Flaground/backend/module/member/controller/dto/response/RecoveryResponse.java
- src/main/java/com/Flaground/backend/module/post/controller/dto/response/SearchResponse.java
- src/main/java/com/Flaground/backend/module/post/domain/enums/SearchOption.java
- src/main/java/com/Flaground/backend/module/post/domain/enums/SearchPeriod.java
- src/main/java/com/Flaground/backend/module/post/domain/repository/implementation/PostRepositoryImpl.java
- src/test/java/com/Flaground/backend/module/post/PostControllerTest.java
- src/test/java/com/Flaground/backend/module/post/PostRepositoryTest.java
> [버그] 게시판 검색 리턴 값 오류 수정 (23.05.19 문희조)

- src/main/java/com/Flaground/backend/global/config/JwtSecurityConfig.java
- src/main/java/com/Flaground/backend/global/config/security/SecurityConfig.java
- src/main/java/com/Flaground/backend/module/member/domain/Avatar.java
- src/main/java/com/Flaground/backend/module/member/service/MemberService.java
- src/main/java/com/Flaground/backend/module/post/controller/dto/response/GetPostResponse.java
- src/main/java/com/Flaground/backend/module/post/domain/repository/implementation/PostRepositoryImpl.java
- src/main/java/com/Flaground/backend/module/post/service/PostService.java
- src/test/java/com/Flaground/backend/module/post/PostControllerTest.java
- 조회 시 키값 넘기도록 수정
- 조회 시 조회수 카운팅 수정
- 데드코드 삭제
> [수정, 버그] 게시글 조회 수정 (23.06.02 문희조)

- src/main/java/com/Flaground/backend/module/admin/controller/AdminController.java
- src/main/java/com/Flaground/backend/module/admin/service/AdminService.java
- src/main/java/com/Flaground/backend/module/report/service/ReportService.java
- 신고 처리하기 추가
- 관리자 API swagger 반영
> [추가] 신고 단건, 전체 처리 구현 (23.06.07 문희조)

- src/main/java/com/Flaground/backend/global/exception/ErrorResponse.java
- src/main/java/com/Flaground/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/Flaground/backend/global/exception/domain/CustomBadCredentialException.java
- src/main/java/com/Flaground/backend/module/activity/controller/ActivityController.java
- src/main/java/com/Flaground/backend/module/activity/controller/dto/response/ActivityDetailResponse.java
- src/main/java/com/Flaground/backend/module/activity/controller/mapper/ActivityMapper.java
- src/main/java/com/Flaground/backend/module/activity/domain/Activity.java
- src/main/java/com/Flaground/backend/module/activity/domain/ActivityData.java
- src/main/java/com/Flaground/backend/module/activity/domain/ActivityInfo.java
- src/main/java/com/Flaground/backend/module/activity/domain/repository/ActivityRepositoryCustom.java
- src/main/java/com/Flaground/backend/module/activity/domain/repository/MemberActivityRepositoryCustom.java
- src/main/java/com/Flaground/backend/module/activity/domain/repository/implementation/ActivityRepositoryImpl.java
- src/main/java/com/Flaground/backend/module/activity/domain/repository/implementation/MemberActivityRepositoryImpl.java
- src/main/java/com/Flaground/backend/module/activity/service/ActivityService.java
- src/main/java/com/Flaground/backend/module/activity/service/MemberActivityService.java
- src/test/java/com/Flaground/backend/module/activity/ActivityRepositoryTest.java
- src/test/java/com/Flaground/backend/module/activity/ActivityServiceTest.java
- 외래키 제약 에러 대응 (활동 삭제 시 외래키 모두 제거)
- 엔티티 보호를 위한 추상 객체 추가 (ActivityData)
- ErrorResponse 생성자 제거, 팩토리 메서드로 수정
> [추가, 수정] Activity 추상화 추가, 외래키 제약 에러 수정 (23.06.08 문희조)
